theme: jekyll-theme-hacker
title: Seed packages for underprivileged Filipino tech talent - devseed.ph
description: We are a social enterprise that provides free laptops, mentorship and a community for underprivileged but passionate Filipinos who want to code or build. 